Users/manan/broker insert cars
Mums-Who-Code/CarApp pull request #10
Opened 2021-12-04 02:07 UTC by MananSThakkar

2021-12-04 16:47 UTC, ShriHumrudha requested changes

2021-12-04 16:47 UTC, ShriHumrudha commented on CarApp.ConsoleApp/Models/Cars/Cars.cs
> +    internal class Cars
The model holds just one entity so go with singular 'Car'

2021-12-04 16:47 UTC, ShriHumrudha commented on CarApp.ConsoleApp/Models/Cars/Cars.cs
> +        public int vinNumber { get; set; }
The properties should be in Camel Casing - VinNumber, with a capital V

2021-12-04 16:47 UTC, ShriHumrudha commented on CarApp.ConsoleApp/Models/Cars/Cars.cs
> +namespace Car.ConsoleApp.Models.Cars
The namespace should be - CarApp.ConsoleApp.Models.Cars

2021-12-04 16:47 UTC, ShriHumrudha commented on CarApp.ConsoleApp/Broker/Storages/StorageBroker.Cars.cs
> +        List<Cars> _Cars = new List<Cars>();
We can skip the _, just Cars

2021-12-06 20:18 UTC, ShriHumrudha commented
Your PR title should be with 'BROKER:' prefix,

2021-12-07 00:14 UTC, ShriHumrudha requested changes

2021-12-07 00:14 UTC, ShriHumrudha commented on CarApp.ConsoleApp/Models/Car/Car.cs
> +namespace CarApp.ConsoleApp.Models.Car
The folder name has to be plural - Cars

2021-12-07 02:10 UTC, MananSThakkar commented on CarApp.ConsoleApp/Models/Car/Car.cs
> +namespace CarApp.ConsoleApp.Models.Car
Update the Model folder to "Cars"

2021-12-07 02:33 UTC, ShriHumrudha requested changes

2021-12-07 02:33 UTC, ShriHumrudha commented on CarApp.ConsoleApp/Broker/Storages/IStorageBroker.Car.cs
> +namespace CarApp.ConsoleApp.Broker.Storages
Brokers should be plural

2021-12-07 02:35 UTC, MananSThakkar commented on CarApp.ConsoleApp/Broker/Storages/IStorageBroker.Car.cs
> +namespace CarApp.ConsoleApp.Broker.Storages
Updated folder name

2021-12-07 02:40 UTC, ShriHumrudha approved these changes

2021-12-07 02:40 UTC, ShriHumrudha commented on CarApp.ConsoleApp/Brokers/Storages/IStorageBroker.Car.cs
> +namespace CarApp.ConsoleApp.Broker.Storages
Even the namespace has to be updated - 'Brokers'

2021-12-07 02:40 UTC, merged